kind: pipeline
type: vm
name: default

pool:
    use: testpool

steps:
    - name: Run Lacework SCA
      image: lacework/lacework-cli
      environment:
          LW_ACCOUNT:
              from_secret: lacework_account
          LW_API_KEY:
              from_secret: lacework_api_key
          LW_API_SECRET:
              from_secret: lacework_api_secret
      commands:
          - lacework --noninteractive component install sca
          - lacework --noninteractive version
          - lacework --noninteractive component list
          - lacework --noninteractive sca git . --save-results -o sca.sarif --formats sarif --deployment ci --secret
      when:
          branch:
              - main
    - name: WebGoat mvn compile
      image: maven:latest
      commands:
          - mvn clean compile
