# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
- task: SynopsysDetectTask@7
  inputs:
    BlackDuckService: 'kyle-bd'
    DetectArguments: |
      --blackduck.trust.cert=true
      --detect.project.name=WebGoat-Azure
      --detect.project.version.name=Released_1.0
      --detect.project.version.phase=RELEASED
      --detect.code.location.name=WebGoat-Released_1.0-ADO
    DetectVersion: 'latest'
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
