# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: SynopsysDetectTask@7
  inputs:
    BlackDuckService: 'us1a-imp-hub11'
    DetectArguments: |
      --blackduck.trust.cert=true
      --detect.project.name=WebGoat-Azure
      --detect.project.version.name=Released_1.0
      --detect.project.version.phase=RELEASED
      --detect.code.location.name=WebGoat-Released_1.0-ADO
      --detect.diagnostic=true
    DetectVersion: 'latest'
