version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - REGION=ap-northeast-2
      - echo Nothing to do in the pre_build phase…
  build:
    commands:
      - echo Build started on `date`
      - pwd && ls && whoami
      - ./mvnw clean install
  post_build:
    commands:
      - echo Build completed on `data`
artifacts:
  files:
    - target/webgoat-2023.6-SNAPSHOT.jar
    - appspec.yml
    - start.sh
