version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase…
  build:
    commands:
      - echo Build started on `date`
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION!!!!!!!!!!!!
      - aws codebuild batch-get-projects --names Build     
      - pwd && ls && whoami
      - ./mvnw clean install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: none
  files:
    - target/*.jar
    - appspec.yml
    - scripts/**
    - buildspec-owasp-zap.yml
  discard-paths: yes
