version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - pip3 install --upgrade git+https://github.com/Grunny/zap-cli.git
      - export PATH=$PATH:$HOME/.local/bin
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase…
  build:
    commands:
      - echo Build started on `date`
      - pwd && ls && whoami
      - ./mvnw clean install
  post_build:
    commands:
      - aws ssm send-command \
      --document-name "AWS-RunShellScript" \
      --targets "Key=instanceids,Values=i-0594735cb2923b48d" \
      #--parameters "commands=['python3 zap_start.py', 'python3 zap_scan.py']" \
      --region ap-northeast-2
      - echo Build completed on `date`
artifacts:
  type: none
  files:
    - target/*.jar
    - appspec.yml
    - zap/**/*
    - zap_start.py
    - zap_scan.py
  #discard-paths: yes
