version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - REGION=ap-northeast-2
      - echo Nothing to do in the pre_build phase…
  build:
    commands:
      - echo Build started on `date`
      - pwd && ls && whoami
      - ./mvnw clean install
  post_build:
    commands:
      - echo Build completed on `date`
      - echo -n "{ \"messageType\": \"CodeScanReport\", \"reportType\": \"OWASP-Zap\"," > payload.json
      - echo -n " \"createdAt\": $(date +\"%Y-%m-%dT%H:%M:%S.%3NZ\")," >> payload.json
      - echo -n " \"source_repository\": $CODEBUILD_SOURCE_REPO_URL," >> payload.json
      - echo -n " \"source_branch\": $(git rev-parse HEAD)," >> payload.json
      - echo -n " \"build_id\": $CODEBUILD_BUILD_ID," >> payload.json
      - echo -n " \"source_commitid\": $CODEBUILD_RESOLVED_SOURCE_VERSION," >> payload.json
      - echo " \"report\": . }" >> payload.json
      - S3_BUCKET_NAME="codebuild-test-hbucket"
      - S3_OBJECT_KEY="log/zap-scan-results.json"
      - aws s3 cp payload.json s3://$S3_BUCKET_NAME/$S3_OBJECT_KEY
      - echo "Report uploaded to S3: s3://$S3_BUCKET_NAME/$S3_OBJECT_KEY"
artifacts:
  files:
    - target/webgoat-2023.6-SNAPSHOT.jar
    - appspec.yml
    - start.sh
