version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase…
  build:
    commands:
      - echo Build started on `date`
      - pwd && ls && whoami
      - ./mvnw clean install
      - java -jar webgoat-2023.6-SNAPSHOT.jar > /dev/null 2> /dev/null < /dev/null &
      - aws lambda invoke --function-name zap-scan --outfile codebuild-result.json
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: none
  files:
    - target/*.jar
    - appspec.yml
    - scripts/**
  discard-paths: yes
