post_build:
  commands:
    - |
      jq "{ \"messageType\": \"CodeScanReport\", \"reportType\": \"OWASP-Zap\", \
      \"createdAt\": $(date +\"%Y-%m-%dT%H:%M:%S.%3NZ\"), \"source_repository\": env.CODEBUILD_SOURCE_REPO_URL, \
      \"source_branch\": env.CODEBUILD_SOURCE_VERSION, \
      \"build_id\": env.CODEBUILD_BUILD_ID, \
      \"source_commitid\": env.CODEBUILD_RESOLVED_SOURCE_VERSION, \
      \"report\": . }" zap-scan-results.json > payload.json

      # S3 버킷 정보
      S3_BUCKET_NAME="codebuild-test-hbucket"
      S3_OBJECT_KEY="log/zap-scan-results.json"

      # AWS CLI를 사용하여 S3로 보고서 전송
      aws s3 cp zap-scan-results.json s3://$S3_BUCKET_NAME/$S3_OBJECT_KEY

      echo "Report uploaded to S3: s3://$S3_BUCKET_NAME/$S3_OBJECT_KEY"
