version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase…
      # OWASP ZAP 설치
      - wget -q https://github.com/zaproxy/zaproxy/releases/download/v2.14.0/ZAP_2.14.0_Linux.tar.gz
      - tar -zxvf ZAP_2.14.0_Linux.tar.gz
      - rm ZAP_2.14.0_Linux.tar.gz
      - cd ZAP_2.14.0
      - chmod +x ./zap.sh

      # webgoat 실행
      - nohup java -jar "$DEPLOY_JAR" --server.port=8080 --server.address=43.200.16.60 > /dev/null 2> /dev/null < /dev/null &
  build:
    commands:
      - echo Build started on `date`
      - pwd && ls && whoami
      - ./mvnw clean install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: none
  files:
    - target/*.jar
    - appspec.yml
    - scripts/**
    - buildspec-owasp-zap.yml
  discard-paths: yes
