version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
       - pip3 install zap-cli==0.10.0
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase…
  build:
    commands:
      - echo Build started on `date`
      - pwd && ls && whoami
      - ./mvnw clean install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: none
  files:
    - target/*.jar
    - appspec.yml
    - zap/**
    - zap-cli
    - zap.sh
    - zap_start.py
    - zap_scan.py
  #discard-paths: yes
