version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - REGION=ap-northeast-2
      - echo "Pre-build phase..."
  build:
    commands:
      - echo "Running OWASP ZAP scan..."
      - sudo yum update -y
      - sudo yum install -y zaproxy
      - zap-cli --version
      - ./run_zap_scan.sh
  post_build:
    commands:
      - echo "Post-build phase..."
      - aws s3 cp zap-scan-results.json s3://codebuild-test-hbucket
