version: 0.2
phases:
  install:
    commands:
      - echo "install phase....."
  pre_build:
    commands:
      - echo "pre build phase....."
  build:
    commands:
      # aws lambda invoke --function-name zap-scan --invocation-type RequestResponse --log-type Tail /tmp/${report_filename}
      #- sudo yum -y update
      #- sudo yum install -y tree
      #- tree -L 2
  post_build:
    commands:
      - aws ssm send-command --document-name "AWS-RunShellScript" --targets "Key=instanceids,Values=i-0594735cb2923b48d" --parameters "commands=['python3 /home/ec2-user/zap_start.py', 'python3 /home/ec2-user/scan.py']" --region ap-northeast-2
      - echo Build completed on `date`
