version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Pre-build phase..."
      - apt-get update
      - apt-get install -y zaproxy
  build:
    commands:
      - echo "Running OWASP ZAP scan..."
      - ./run_zap_scan.sh
      - aws s3 cp zap-scan-results.json s3://codebuild-test-hbucket/zap-results/
