version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - REGION=ap-northeast-2
      - echo Nothing to do in the pre_build phase…
  build:
    commands:
      - echo Build started on `date`
      - pwd && ls && whoami
      - ./mvnw clean install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/webgoat-2023.6-SNAPSHOT.jar
    - echo Artifacts...
    - build/libs/*.jar 
    - appspec.yml   # CodeDeploy 적용 시 추가
    - scripts/**    # CodeDeploy 적용 시 추가
  discard-paths: yes
