version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - REGION=ap-northeast-2
      - echo "Pre-build phase..."
  build:
    commands:
      - echo "Running OWASP ZAP scan..."
      - echo "Installing OWASP ZAP..."
      - sudo yum update -y
      - sudo yum install -y java-1.8.0-amazon-corretto
      - sudo yum install -y wget
      - wget https://github.com/zaproxy/zaproxy/releases/download/v2.10.0/ZAP_2.10.0_Linux.tar.gz
      - tar -xzf ZAP_2.10.0_Linux.tar.gz
      - export PATH=$PATH:$PWD/ZAP_2.10.0
      - ./run_zap_scan.sh
  post_build:
    commands:
      - echo "Post-build phase..."
      - aws s3 cp zap-scan-results.json s3:::codebuild-test-hbucket
artifacts:
  files: '**/*'
