jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: echo "Thiss is a build step"

  test:
    machine: true
    steps:
      - checkout
      - run: echo "This is a test step"

  odc-backend:
    machine: true
    steps:
      - checkout

      - run: docker run --rm -v $(pwd):/src owasp/dependency-check --scan /src --format "CSV" --project "Webgoat" --failOnCVSS 8 --out /tmp

      - store_artifacts:
          path: /tmp/dependency-check-report.csv
          destination: depcheck-artifact

workflows:
  version: 2
  webgoat:
    jobs:
      - build
      - test:
          requires:
            - build

      - odc-backend:
          requires:
            - test