name: "Pull requests build"
on:
  pull_request:
    paths-ignore:
      - '.txt'
      - 'LICENSE'
      - 'docs/**'

jobs:
  pr-build:
    if: >
      github.event_name == 'pull_request' && !github.event.pull_request.draft && (
        github.event.action == 'opened' ||
        github.event.action == 'reopened' ||
        github.event.action == 'synchronize'
      )
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          architecture: x64

      - name: Cache Maven packages
        uses: actions/cache@v3.3.1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Code Scanning
        uses: github/codeql-action/analyze@v1

      - name: Build with Maven
        run: mvn --no-transfer-progress verify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          publish_dir: ./target/webgoat

      - name: Update GitHub Pages Deployment
        run: |
            git config --global user.name "mrping007"
            git config --global user.email "mrpingp03@gmail.com"
            git checkout gh-pages
            git add .
            git commit -m "Update GitHub Pages deployment"
            git push origin gh-pages