name: FOSSA scan

on:
  push:
    branches: [ "develop" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    env:
      FOSSA_API_KEY: ${{secrets.FOSSA_API_KEY}}

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3
            
      - name: "Run FOSSA CLI"
        run: |
            echo "Inside CLI"
            curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | sudo bash
            fossa analyze
