name: CI-pec

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ShiftLeftSecurity/scan-action@master
        env:
          VDB_HOME: ${{ github.workspace }}/vdb
          WORKSPACE: https://github.com/${{ github.repository }}/blob/${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          type: "credscan,java,depscan,bash,yaml"
          output: reports
      - name: Upload scan reports
        uses: actions/upload-artifact@v1.0.0
        with:
          name: shiftleft-scan-reports
          path: reports
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
