name: Node.js Tests with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: docker.io/fortifydocker/scancentral-sast-sensor:23.1.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Wait for services to start
        run: sleep 10s

      - name: Run tests
        run: docker exec $(docker ps -qf name=node-app-container) npm test

  cleanup:
    needs: [container-test-job]
    runs-on: ubuntu-latest
    steps:
      - name: Stop and remove Docker container
        if: ${{ always() }}
        run: |
          docker stop ${{ needs.build_and_test.outputs.container_id }}
          docker rm ${{ needs.build_and_test.outputs.container_id }}
