name: Node.js Tests with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Wait for services to start
      run: sleep 10s
    - name: ls
      run: ls

  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: docker.io/fortifydocker/scancentral-sast-sensor:23.1.0
      credentials:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWD }}
      volumes:
      - ./:/app/sca/
    steps:
      - name: ls
        run: ls /app/sca/

  cleanup:
    needs: [container-test-job]
    runs-on: ubuntu-latest
    steps:
      - name: Stop and remove Docker container
        if: ${{ always() }}
        run: |
          docker stop ${{ needs.build_and_test.outputs.container_id }}
          docker rm ${{ needs.build_and_test.outputs.container_id }}
