name: Node.js Tests with Docker

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: docker.io/fortifydocker/scancentral-sast-sensor:23.1.0
      options: --user root
      credentials:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWD }}
      #volumes:
      #- ./:/app/sca/
    #defaults:
    #  run:
    #    shell: bash
    steps:
      - name: install tar
        run: yum install tar
      - name: Testes
        run: (which tar && echo Found SCA) || (echo No SCA)
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Wait for services to start
        run: sleep 10s
      - name: ls
        run: ls
      - name: Test SCA
        run: echo 'ls /app/sca/'
        #(ls /app/sca/ && echo Found SCA) || (echo No SCA)

  cleanup:
    needs: [container-test-job]
    runs-on: ubuntu-latest
    steps:
      - name: Stop and remove Docker container
        if: ${{ always() }}
        run: |
          docker stop ${{ needs.build_and_test.outputs.container_id }}
          docker rm ${{ needs.build_and_test.outputs.container_id }}
