name: Synopsys Security Testing

on:  
  workflow_dispatch:
  push:
    # At this time, it is recommended to run Polaris only on pushes to main branches
    # Pull request analysis will be supported by Polaris in the future
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
      -   uses: actions/checkout@v3
      -   name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
              distribution: 'temurin'
              java-version: 17
              architecture: x64
      -   name: Cache Maven packages
          uses: actions/cache@v3.2.5
          with:
              path: ~/.m2
              key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
              restore-keys: ${{ runner.os }}-m2-
      -   name: Build with Maven
          run: mvn --no-transfer-progress verify

      - name: Synopsys Action
        uses: synopsys-sig/synopsys-action@v1.0.0
        with:
          polaris_serverUrl: ${{ secrets.POLARIS_SEVER_URL }}
          polaris_accessToken: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polaris_application_name: "APAC-SG-github-demo2"
          polaris_project_name: "miniJS"
          polaris_assessment_types: '["SAST", "SCA"]'

          

        
