name: Node.js Tests with Docker

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: pwd
      run: pwd
    - name: ls
      run: ls /home/runner/work/WebGoat/WebGoat
      
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: docker.io/evernow/fortify-sca:23.1
      options: --user root
      credentials:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWD }}
      #volumes:
      #- /home/runner/work/WebGoat/WebGoat:/tmp
    #defaults:
    #  run:
    #    shell: bash
    steps:
      - name: Testes
        run: |
          systemctl status firewalld
          cat /etc/os-release
          yum install -y tar gzip
          echo $PATH
          ls -la /opt/fortify/bin
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run fortifyupdate
        run: fortifyupdate
      - name: Run Fortify SCA clean
        run: sourceanalyzer -b webgoat -clean
      - name: Run Fortify SCA translate
        run: sourceanalyzer -b webgoat .
      - name: Run Fortify SCA scan
        run: sourceanalyzer -b webgoat -scan -f webgoat.fpr
          
        #(ls /app/sca/ && echo Found SCA) || (echo No SCA)

  cleanup:
    needs: [container-test-job]
    runs-on: ubuntu-latest
    steps:
      - name: Stop and remove Docker container
        if: ${{ always() }}
        run: |
          docker stop ${{ needs.build_and_test.outputs.container_id }}
          docker rm ${{ needs.build_and_test.outputs.container_id }}
