name: Synopsys Security Testing

on:  
  workflow_dispatch:
  push:
    # At this time, it is recommended to run Polaris only on pushes to main branches
    # Pull request analysis will be supported by Polaris in the future
    branches: [ master, main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: GitHub Action for Maven
        # You may pin to the exact commit or the version.
        # uses: LucaFeger/action-maven-cli@765e218a50f02a12a7596dc9e7321fc385888a27
        uses: LucaFeger/action-maven-cli@1.1.0

      - name: Synopsys Action
        uses: synopsys-sig/synopsys-action@v1.0.0
        with:
          polaris_serverUrl: ${{ secrets.POLARIS_SEVER_URL }}
          polaris_accessToken: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polaris_application_name: "APAC-SG-github-demo2"
          polaris_project_name: "miniJS"
          polaris_assessment_types: '["SAST", "SCA"]'

          

        
