name: Node.js Tests with Docker

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: docker.io/fortifydocker/scancentral-sast-sensor:23.1.0
      env: 
        PATH: /snap/bin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/app/sca/bin
      options: --user root
      credentials:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWD }}
      #volumes:
      #- ./:/app/sca/
    #defaults:
    #  run:
    #    shell: bash
    steps:
      - name: Testes
        run: (which tar && echo Found SCA) || (echo No SCA)
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Wait for services to start
        run: sleep 10s
      - name: ls
        run: ls
      - name: Test SCA
        run: echo 'ls /app/sca/'
        #(ls /app/sca/ && echo Found SCA) || (echo No SCA)

  cleanup:
    needs: [container-test-job]
    runs-on: ubuntu-latest
    steps:
      - name: Stop and remove Docker container
        if: ${{ always() }}
        run: |
          docker stop ${{ needs.build_and_test.outputs.container_id }}
          docker rm ${{ needs.build_and_test.outputs.container_id }}
