name: Truffle Docker Manual
on: [push, pull_request]
jobs:
  TruffleHog:
    name: Truffle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Docker
        run: |
          docker run -t -v "$PWD:/pwd" ghcr.io/trufflesecurity/trufflehog:latest filesystem --directory /pwd
